# Generated by Django 5.2.7 on 2025-11-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='oub_date',
            new_name='pub_date',
        ),
    ]
